### ISSUE TITLE
Privacy + Legal page copy

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#115]
We need some words for the privacy and legal page. We want to add analytics so we'll need to describe that.

The things which will affect privacy:
- Analytics (cookies, tracking)
- A contact form which will store the results in another system, e.g. google forms, typeform, email inboxes etc

**Comment by katquatermass** [comment]
There's wording in the Contemplating Action page we could borrow that Neil signed off - I can't dig up a link right now but will try tomorrow

**Comment by katjam** [comment]
http://www.contemplatingaction.org.uk/#/privacy-policy

Contemplating Action Privacy Policy and Cookies
This policy relates to www.contemplatingaction.org.uk (“the Site”) which is owned by Neontribe ltd and related activity

Neontribe ltd trading as Neontribe
Registered as a limited company in England & Wales
Business registration: 06165574
Registered office: 106 Lincoln St. Norwich, Norfolk, NR2 3LB.
What information is collected?
We collect the following information from people who use this website:

Email addresses of people who communicate with us via email
Information volunteered by people in the course of using of the website (predominantly survey responses)
Analytics and tracking data about people’s site usage
How is the information used?
Neontribe uses the information you provide to:

Improve the usability of the Site
Help design future projects
Contribute to research about third sector use of digital
Send you any information you have requested relating to the Contemplating Action project
If you chose to give us contact details we will only contact you in relation to these four things. You can also tell us if you no longer wish to receive information from Neontribe by replying to any email from us with the subject line Unsubscribe, or sending a message to info@neontribe.co.uk requesting to unsubscribe.

Information that is identifiable as relating to you (i.e. it has not been edited to make it anonymous) is not shared with or sold to other organizations for commercial purposes, other than under the following circumstances:

If it is necessary to share information in order to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of Terms of Service, or as otherwise required by law.
If we transfer information about you if Neontribe is acquired by or merged with another organisation, other than an organisation established by us and controlled by us.
You have explicitly chosen to have us share the information with CAST - the centre for acceleration of social technology whilst giving us the information - in which case it will be freely shared with them.
Where is the information stored?
On our computers
On our survey provider Typeform’s servers. For more information see Typeform's privacy policy.
In Google Analytics. For more information see Google's privacy policy.
By our partner CAST on their servers if you have explicitly expressed the desire to share your information with them whilst using our site. For more information see CAST's privacy policy.
Your rights
We guarantee to meet your rights in compliance with GDPR. Find out about those rights from the ICO GDPR indvidual rights guide. To exercise any of your rights, please contact us at hello@contemplatingaction.org.uk

Use of cookies
Cookies are pieces of information that a website transfers to your hard drive. Most web browsers automatically accept cookies, but if you prefer, you can change your browser to prevent that and will still be able to use the site.

Contemplating Action uses cookies to:

Monitor the number of visitors to our website
Monitor how users use our website, i.e. which pages they have accessed
To help improve our website
For more data on Cookies visit www.aboutcookies.org. In addition to detailing extensive information on cookies this site also provides explanations on how to disable cookies on your computer.
Your acceptance of these terms
By using this site, you consent to the collection and use of this information by Neontribe and to our privacy policy. Please send any questions, concerns or comments you have about these policies to info@neontribe.co.uk

**Comment by neil-dabson** [comment]
Neontribe Privacy Policy and Cookies
This policy relates to www.neontribe.co.uk and related sub-domains of neontribe.co.uk (“the Site”) which is owned by Neontribe ltd and related activity.
Neontribe ltd trading as Neontribe
Registered as a limited company in England & Wales
Business registration: 06165574
Registered office: 106 Lincoln St. Norwich, Norfolk, NR2 3LB.

What information is collected?
We collect the following information from people who use this website:
Email addresses of people who communicate with us via email.
Information volunteered by people in the course of using of the website.
Analytics and tracking data about people’s site usage.

How is the information used?
Neontribe uses the information you provide to:
Improve the usability of the Site.
Help design future projects.
Offer employment and/or other events.

If you chose to give us contact details we will only contact you in relation to these four things. You can also tell us if you no longer wish to receive information from Neontribe by replying to any email from us with the subject line Unsubscribe, or sending a message to privacy@neontribe.co.uk requesting to unsubscribe.
Information that is identifiable as relating to you (i.e. it has not been edited to make it anonymous) is not shared with or sold to other organizations for commercial purposes, other than under the following circumstances:
If it is necessary to share information in order to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of Terms of Service, or as otherwise required by law.
If we transfer information about you if Neontribe is acquired by or merged with another organisation, other than an organisation established by us and controlled by us.

Where is the information stored?
On our computers.
On Google computers within Neontribe’s Google Apps for Business account.
In Google Analytics. For more information see Google's privacy policy. https://policies.google.com/privacy?hl=en

Your rights
We guarantee to meet your rights in compliance with GDPR. Find out about those rights from the ICO GDPR individual rights guide. To exercise any of your rights, please contact us at privacy@neontribe.co.uk
Use of cookies
Cookies are pieces of information that a website transfers to your hard drive. Most web browsers automatically accept cookies, but if you prefer, you can change your browser to prevent that and will still be able to use the site.
Neontribe uses cookies to:
Monitor the number of visitors to our website.
Monitor how users use our website, i.e. which pages they have accessed.
To help improve our website.
For more data on Cookies visit www.aboutcookies.org. In addition to detailing extensive information on cookies this site also provides explanations on how to disable cookies on your computer.

Your acceptance of these terms
By using this site, you consent to the collection and use of this information by Neontribe and to our privacy policy. Please send any questions, concerns or comments you have about these policies to privacy@neontribe.co.uk
