### ISSUE TITLE
Create the MVP paper prototype

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#20]
**What needs doing?**

Create a MVP paper prototype based on the meeting we had.

**Plan**

- [x] Create a MVP paper prototype.

**Link to Paper Prototype**

https://realtimeboard.com/app/board/o9J_ky7fu5U=/

We've created the paper prototype based on the basic features and pages we discussed in the meeting. We would like to know if you think there are any important content elements missing from the MVP.

**Comment by katjam** [comment]
Considering our top priority story is about conveying company culture and individuality, and since we've not yet producd blog content that covers the breadth of what we do and who we are: a people overview page might be an easier way to achieve that for the MVP.

Also MVP wise - the blog part involves wiring up the wordpress into our site and flow.

Agree that blogs are important - but we might not be ready with that content yet. If it is higher priority than people - maybe we need to cover off that individual/ culture story with some other copy - and leave both blog and people out of the initial release?

Otherwise. Looks ace! Great work.

**Comment by katquatermass** [comment]
I agree that people higher priority than blogs overall. I think we all got swayed by Harry too far on that one.

I think the pages themselves deliver well apart from the landing page.

I don't think featured projects or featured blog are useful for answering stories on a landing page for a number of reasons.  1) we have 3 (broad) types of important user - it will be very hard to pick things that meet all of their needs (Potential clients; potential employees and slightly less priority potential partners in the community for conferences and training etc) 2) It seems to me that in terms of MVP - a "pull in featured" tool is way higher effort than "some copy and an image and a link or button" - although that could easily be my misunderstanding of development  3) Keeping them fresh and up to date  - and rethinking the balance of all those user types each time we have an instinct to change the featured ones is resource heavy.

I would like to answer user stories on arrival on a landing page by offering information that each user is looking for (mostly reassurance to their first story - eg clients "do we do the sort of work they want" potential employees "can they apply here" and the third type rather more varied by "do we do outreach") and a call to action either to get in touch or to go to the place where you can get more reassurance.   I think these are hard to display on a prototype because they are so reliant on a strong piece of copy - but could be shown as a way of breaking up a page to give those 3 different pieces of reassurance (even if in MVP two of them lead to projects they are still 3 different starting points)

**Comment by katjam** [comment]
Agree with @katquatermass on the featured sections - I was worried about how we choose them and that any system would alienate some of our audience (like the problem we have with the current site). I didn't mention in my initial response though because I think the blog vs people is an issue to crack first before we can re-tackle the landing page.

**Comment by katjam** [comment]
Another concern is that without the filtering capability - we're in the same situation as our current website in terms of the blog and project postings. And maybe even worse off since even if it's not at first obvious, the current site has blog tags.

We 'could' hit a lot if our user story goals if the whole site were blogs... but relying on blogs to deliver our core messages is maybe too easy, like an FAQ section - a bag of verbose, miscellaneous stuff - the hard part is to make it easy to find what people are looking for.

Looking at it that way - blogs have to be so carefully curated that they might as well be 'core' content - authored by a particular person in their voice - which might be a neat way to get our diversity point across? If we set it up like that with strong enough guidelines for each type of content, it might work - and would reflect our company structure that we are a collective working together rather than a 'company with a brand'.

**Comment by Nikomus** [comment]
I agree with People being much more important than Blogs. A People page satisfies a number of our top-pick user stories, and construction wise feels like it should come first. If we eventually want everything to be linked up, then a blog would belong to a person.

**Comment by katquatermass** [comment]
I think that delivering projects through a blog like system that would allow tagging - and inviting leads to contribute would be a stronger solution that doing it all through blogs which are - in general - longer than we need to convey the core trusts and confidences our users want. (even at short blog length of 400-600 words)

**Comment by katquatermass** [comment]
Hmmm I thought this was supposed to nest comments better than trello - am I doing it wrong!

**Comment by HedgehogHolly** [comment]
We had a chat with Harry after the meeting and he gave use the indication that blogs were more important than the people page at this stage. So thats the only reason we haven't added a people page on the prototype, same applies to the filtering option on blogs/projects.

**Comment by katjam** [comment]
@katquatermass Sadly - no - the threading is better on Jira but not here.

**Comment by katjam** [comment]
For historical info related to MVP contents see:
#21 #22 #23 #24 #26 #25 #27

**Comment by gingerbreadpup** [comment]
> Furthermore, I also wonder if the development time implicit in "featured" blocks on the home page is worth the candle, given the difficulty of choosing a post or project to feature - maybe we can populate that front page with some well-chosen calls to action instead? Which might come close to @katjam 's user-led home page, which I'd still like to explore as well...

I'm on board with the idea of the user-led home page. I'd like to see our home page addressing some of the most important user stories, so some excellent copy + calls to action. To avoid the front page just being all text though, we _could_ still create a section to showcase a project(s) just using static text/images. This would keep dev time to a minimum and might be a decent MVP solution until we can replace it with non-static content in a later release.

Let's make sure we look at the pain points highlighted by Naomi and make sure we're addressing those too.

**Comment by katjam** [comment]
Historical info from https://trello.com/c/8YwxfpYy/86-questions-from-messy-prototyping-board

![screenshot_20181213_113853](https://user-images.githubusercontent.com/861172/49936364-ada6b500-fecb-11e8-84dd-83301de4a54e.png)

![screenshot_20181213_113959](https://user-images.githubusercontent.com/861172/49936414-d4fd8200-fecb-11e8-97f1-3cc0ba588906.png)
