### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#232]
We currently support evergreen browsers, do we want to support IE11 users?

### Plan
- [x] Consider IE11 usage
- [ ] Test in IE11

**Comment by Kurgol** [comment]
* All people on "the tribe" page are full colour rather than b&w on ie11.
* When you click someone on "the tribe" page it doesn't flip to the text description, it just flips the image and tagline below it around mirrored. After you have done this further clicks do not return the image to its initial state.
* There is no menu squiggle under the nav elements at the top of the page

**Comment by Kurgol** [comment]
the /blog endpoint is returning not a number for the age of all blog posts (ie11)

**Comment by RpprRoger** [comment]
Thanks @Kurgol! I've put all of these into either browser bugs to do before release and some to do after. They're mostly arbitrary splits
