### ISSUE TITLE
Create and Explore Visual Styles

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#36]
**What needs doing?**
Discuss what theme is generally favoured and what should be the next step

**Plan**
- [x] Create a varied set of styles using mood-board theme.

**Links to designs**
- [Dark Theme](https://drive.google.com/file/d/1504yB18u9GREhGaqA8rYsMStZpBoSwrL/view?usp=sharing)
- [Gradient Theme](https://drive.google.com/file/d/1vp0mCprNGHqFYKzvzNpYQ5H_oTJ_4mPp/view?usp=sharing)
- [Minimal Theme](https://drive.google.com/file/d/1U5kPmyXAtBsULcmmtqhCzTRFkSFIyfTr/view?usp=sharing)

**Comment by falconx** [comment]
(fyi) just in case we weren't aware of this capability: we can use CSS to apply a mask images to make them hexagons.

**Comment by falconx** [comment]
without the rigid square boundaries, the content on the Minimal Theme seems to flow more naturally.

**Comment by jermyk** [comment]
Mmmm tricky, I quite like the dark as it really makes it look "neon"

**Comment by katjam** [comment]
- I like the fonts on the minimal theme.
- I think the dark theme makes the colours pop and looks more tech-y (if that's a thing) - but I like the softness and friendliness of the minimal theme too
- Like Matt, I'm not sure about the text and shapes overlapping on the minimal theme - I like text on a uniform background

**Comment by alexalala** [comment]
Dark is my fave! 

https://css-tricks.com/ these guys just redesigned their site with a darker theme and it looks pretty smart. Love the hover effect on the top nav!

**Comment by rjb-04** [comment]
They look great Holly!!!! My favs are the dark and minimal theme. I agree with Katja that the dark theme looks more tech-y, but also like the minimal theme. Another background suggestion, a dark purple background, a bit softer than the off black maybe?

I personally like the font on the dark theme, but then I have a strange bias against serif fonts. 

I also agree with everyone about the overlapping, text on uniform background seems like the way to go.

**Comment by katquatermass** [comment]
I like all the different fonts, slight preference for the sans serif. 

Whilst I agree with Matt that the page flows more when text not in boxes, I think that the type of content we have may well benefit from the more abrupt separation of boxes (its "skim to pick a bit that interests you type consumption rather than read the whole lot, on the whole) and that saves us the problem of overlay so it might have a double benefit to be using the dark layout.

I think I like the strong look of dark theme, but there is something about the depth suggested by the gradient theme that appeals (reading shading as sophistication where flat colour is less clever/sophisticated perhaps is what is going on in my head)

I like the colour choices for the shapes in the dark theme but there was something about the depth/shade of colour in the Neon examples in the mood boards that is lost when it translates to flat colour.  I presume if it was retained by filling shapes with photographic colour it would  just look ridiculoso busy and drag the eye all sorts of weird ways- so you should ignore me mourning that 80's vibe...

**Comment by katjam** [comment]
@katquatermass I'm pretty sure css (and photoshop) can generate neon-like effects relatively easily if that's what we want.

**Comment by katquatermass** [comment]
Yes - I was assuming it was a "this would looks rubbish even though I think it might look good" rather than "this is hard to do" issue  @HedgehogHolly?

**Comment by katjam** [comment]
I think some small touches (like @alexalala example above) might help to bring more personality/ fun but sensible - and still look good without being overwhelming.

**Comment by HedgehogHolly** [comment]
It depends what you mean by neon, if you mean the sort of glowing edges I think that would disrupt the clean look of flat colours and clean typography. I only know about photoshop's capabilities, not sure what neon effects you can do within CSS.

**Comment by katquatermass** [comment]
Yeah - I think I'm probably wrong. But I don't mean glowing edges, I mean the shapes being windows onto photos of Neon - like each one was a cutout from that original mood board I think.   I suspect it is just a sense of that board having a particularly arty vibe and you are right it might ruin the flat colour simplicity...  move along, nothing to see here...

**Comment by katjam** [comment]
@HedgehogHolly Fair point on the cleanliness. In terms of css capability I think you should assume it can do anything and not let that hold back in your designs.

**Comment by katjam** [comment]
Closing/ Archive for reference. We'll do more work on design once we have more ideas about content.
