### ISSUE TITLE
Create MVP Prototype

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#43]
**What needs doing?**
Create MVP Prototype of front page, how we work and people page

**Plan**
- [x] Create MVP
- [x] @katquatermass writing up missing elements discussed in flow to check if intended part of design
- [ ] @katjam update prototype in Exeter with @HedgehogHolly and @Nikomus when Holly comes to town!

![img_20190206_155144359](https://user-images.githubusercontent.com/41140803/52401306-423b2700-2ab9-11e9-94e1-6f5992b349dd.jpg)
![img_20190206_155042409](https://user-images.githubusercontent.com/41140803/52401304-423b2700-2ab9-11e9-92db-04639baca245.jpg)
![img_20190206_154929966](https://user-images.githubusercontent.com/41140803/52401305-423b2700-2ab9-11e9-9051-f19f15a07bfc.jpg)

**Comment by katjam** [comment]
For reference workshops leading to this MVP here: #40 and original prototypes here: #20

**Comment by HedgehogHolly** [comment]
We might need to add something to the People page that indicates how to join Neontribe. I believe we talked about having a form of some kind?

**Comment by katquatermass** [comment]
@HedgehogHolly checking - are these the pages that are in the folder now with Katja? (so she doesn't have to interrupt MOMO thinking and look)... I have a task to look for things that might not have been clear from Flow workshop so you can check off whether they are a) design choice or b) wasn't clear enough so Katja and Nick can add before testing

**Comment by HedgehogHolly** [comment]
@katquatermass yes those are the ones that are Katja

**Comment by katquatermass** [comment]
Any of these may have been made as a deliberate design decision OR they might be because  "the flow workshop write up was too poor and so didn't realise it was a design goal or question to explore" OR because none of us have thought hard enough about the thing yet...    @HedgehogHolly you could tick off those that are design decisions and add any comments here if you want, but equally I think that the question list makes a good basis for tomorrow's call?   I've grouped all my questions under overall headers. 

**I think these are design decisions**
- [ ] Throughout - Navigation is by text link, not button 
- [ ] Front page - display 1 not 3 employees (MVP may be one selected, future likely to be randomised or a slider)
- [ ] Add projects repository on the bottom of challenges and funders page (because it means that any challenge or project or funder can go to individual page or a set of tagged pages rather than not being sure whether it should go to an individual page or an overall one - and so folk looking for a project do not have to hunt through challenges)
- [ ] Front page - Flow discusses how copy with employee picture might view/read better if broken up not in one block as it will likely be quote plus info - however the choice of square image to match following page probably makes this not possible - so design decision is to do that using text styling rather than breaking around the image


**Checklist of Possible Questions**
- [ ] Front page - Norwich and Exeter in BOTH intro paragraph and footer  - We discussed either or for meeting the "is it the right NT story" rather than both?
- [ ] Front page - It was intended to give users a choice of path ( from the employee image - route could be straight to "work with us" for application OR to meeting more of the team) - there is only one text link - is there another route (eg is the image clickable)?
- [ ] Working page - has lost the great "With Money From" line for Funders - think this is probably due to late write up. The workshop page also has Problems We've Solved instead of Challenges. I would like to discuss but I like the more active titles as a way of pulling flow through.


**Is this the MVP functionality**
- [ ] Meet the tribe page - doesn't have a call to action link to apply on it that would finish the flow for someone who looked at more people before deciding to apply
- [ ] How we work page - doesn't have a call to action link on it for people who now trust us and want to begin a journey
- [ ] Challenge/Solution mechanic - they don't link to further information, 3 display (from a randomised larger pool?).  Alternatives could be... on reveal final part of reveal sentence is a link to further info on the project. Think we have rejected a "see more" option?
- [ ] Funder logos - do not function as links (next steps turns them into links to a tagged collection of projects) 
- [ ] Could the projects themselves be left out of MVP? (The flow session considered that perhaps they could, but Matt made a pretty convincing case not to - and I think the story about finding us after events, when you only remember the project we talked about means keeping them is a good plan
- [ ] Because these come from the flow workshops - contact info is not easily available for people who just want to get in touch.  Is there a good argument for sticking basics in the footer for those who don't want to go on our journeys? 


**What is the intended behaviour**
- [ ] New people page - are we looking at a version that has minimal person info and where the photo tiles turn round to show that similar minimal person info when you click on them? If not that, what is behaviour on that page? Do we envisage going any further through to a more detailed person page as MVP?
- [ ] Presume the "get some text in" is a reason for loosing the hexagons since hexagons are rubbish for text- or maybe just overall design is heading that way anyway?

**Prototype elements**
- [ ] We need some "when actioned this happens" elements - like the solution reveals and when I click on an image or on a see more that doesn't go to a main page

**Comment by HedgehogHolly** [comment]
I've ticked the ones I feel were design choices.

_**"Front page - display 1 not 3 employees"**_ - I believe I did provide an alternative slider with 3 employees that Katja should have, I just didn't photograph it.

_**"Front page - It was intended to give users a choice of path"**_ - there is two links/choices on the page, it might be hard to see but we have "work with us" and "see more about what we do..." 

**_"Working page - has lost the great "With Money From" line for Funders - think this is probably due to late write up."_** - Yes, I think it was just the case of the late write up

_**"Meet the tribe page - doesn't have a call to action link"**_ and _**"How we work page - doesn't have a call to action"**_  - Ah yes I think we forgot to add the google form at the bottom of both those pages to the prototype. That is probably something @katjam will have to add to the prototype

_**"Challenge/Solution mechanic - they don't link to further information"**_ - I think we thought about them linking to the project page they relate to... which I realise now we don't have an individual project page with the prototype (although Steph and I have mocked one up in the past). Which also means that the projects at the bottom of the page currently don't lead anywhere either..

_**"Contact info is not easily available for people who just want to get in touch"**_ - What contact info do you mean? the email is in the header and the addresses are in the footer?

_**"Are we looking at a version that has minimal person info and where the photo tiles turn round to show that similar minimal person info when you click on them"**_ - Yes that was the idea, its similar to how [Creative Sponge](https://www.creativesponge.co.uk/culture) do their people page. This was the solution we came up with as a result of the individual pages not being a part of the MVP. 

_**"Presume the "get some text in" is a reason for loosing the hexagons since hexagons are rubbish for text"**_ - Yes exactly, since the individual page were no longer apart MVP we needed more info on the page and hexagons would have made that difficult. Steph also brought up the fact that in this current prototype there are no other use of hexagons and it might have seemed out of place to use them on this page.

**Comment by katquatermass** [comment]
Cheers @HedgehogHolly have updated lists based on your comments

**Comment by katjam** [comment]
@Nikomus mentions that there was a consensus of not having a footer at some point - because corporate letterhead - and thinking outside the box deign-wise. Not saying we need to do anything about it now - but maybe stop calling it a footer, stop assuming it's on every 'page' view and remember that we want the design of it not to look 'boring/ traditional/ ignore-able'.

**Comment by katquatermass** [comment]
**MVP Prototype updates needed**

Front Page
- [ ] Remove Norwich and Exeter from the copy in top right of front page 
- [ ] Bring 1 challenge/solution pair with a title of A problem we solved onto front page (or 3 pairs in a slider to match person) 
- [ ] ensure that two different calls to action relate to the person element of front page - Meet the team - which goes to top of people page AND Work with us - which goes to location on people page where call to action (go to application form - that won't be the copy try "join us" or similar so it doesn't repeat exact wording of previous button) is located (see next point)
- [ ] Explore contact info display (widget) within footer on landing page at least (make decision of whether it is cross site later) - can it help indicate which is preferred method (eg one solution is with tabs)
- [ ] Redesign front page to fit this in - does it go above or below person and can it share call to action with the current top section (if above person) 
People Page
- [ ] decide where call to action "join us" is located on people page. Does it need copy to go with it?
How we work
- [ ] Rework second page in See more about what we do flow now that it no longer holds challenges/solutions - to include funders logos under "With Money From" and to include projects (all, not having own pages to click into - need to be either fully scrollable or using some mechanic like the people page, but able to display an amount of info per project roughly similar to our current). Let us know if it needs a copy block at all to balance the page out. NO CALL TO ACTION FOR THIS PAGE


@HedgehogHolly hope this makes sense, I'll be in tomorrow if it doesn't

**Comment by HedgehogHolly** [comment]
Wireframes updated with new layout we discussed, the only thing that hasn't been added is a contact info widget as Im not sure what that would look like. @katjam I think you talked about seeing it on a website somewhere, do you have an example? 


---

![front page](https://user-images.githubusercontent.com/41140803/53159810-83a1fb00-35be-11e9-9f26-dabbf77ac7de.png)


---

![the tribe](https://user-images.githubusercontent.com/41140803/53159811-83a1fb00-35be-11e9-9f9a-114820c3cf3e.png)


---

![how we work](https://user-images.githubusercontent.com/41140803/53159812-83a1fb00-35be-11e9-8aa0-f360da0f986d.png)

**Comment by katjam** [comment]
@HedgehogHolly Not sure if I have a particular one in mind for contact widget. Was just an idea to help us get away from the 'standard footer' which I think we previously agreed we didn't want.

I think it'll be interesting to stick the 'leagal required info' at the bottom of the landing page - but not have it on the other pages. That will also force us to be more creative with where/how we display the contact info. It might not be MVP to release with that though.

**Comment by falconx** [comment]
> Was just an idea to help us get away from the 'standard footer' which I think we previously agreed we didn't want
As far as I remember, there wasn't an actually a good argument for this other than to make us consider alternatives? A widget (which we'd presumably show on each page) is an alternative but I don't see how it would provide the user with a better experience? In fact likely be less intuitive.

**Comment by katjam** [comment]
mattlayt [5:22 PM]
> Also considering for MVP - no carousel?
agreed. it's _nice to have_ and doesn't deliver much in terms of _value_.

> Do we then need to add copy and / or button to swap out the random one to make it obvious that it is a random choice?
imo, we don't need to provide any indication that they're randomised but that there should be a single clear call to action for the user to arrive at a view which contains all possible entries. without this, a user may be tempted to repeatedly refresh the page to find an entry they've previously seen.

**Comment by HedgehogHolly** [comment]
![IMG_20190313_122211822](https://user-images.githubusercontent.com/41140803/54278984-d05c6e80-458b-11e9-9393-21d5c26f28ad.jpg)
![IMG_20190313_122351476](https://user-images.githubusercontent.com/41140803/54278994-d5b9b900-458b-11e9-99a4-f23c5328c165.jpg)
![IMG_20190313_122849986](https://user-images.githubusercontent.com/41140803/54278996-d81c1300-458b-11e9-993a-4ce4cafc2095.jpg)
![IMG_20190313_122326221](https://user-images.githubusercontent.com/41140803/54279016-e36f3e80-458b-11e9-9957-9ff7fe13cbbc.jpg)

**Comment by katjam** [comment]
@katquatermass The prototype is complete!

**Comment by katjam** [comment]
We'll test with the 'footer' on every page and the 'footer' only on the landing page.

& Include a deep linked one with the objective of getting in touch.
