### ISSUE TITLE
Prototype User Interface in html/css

### ISSUE THREAD

**Issue by katquatermass** [neontribe/www#51]
**Prototype User Interface in html/css**

**Plan**
- [x] Once wireframe is updated this can began
- [x] Produce visual prototype in sketch
- [x] Check if design meets user stories
- [ ] Produce UI then decide what other support structures are needed to get it to a live deploy

**Comment by katquatermass** [comment]
@HedgehogHolly will lead this phase with support from @falconx

**Comment by HedgehogHolly** [comment]
https://github.com/neontribe/www/issues/50#issue-422786272

**Updating the wireframe based on prioritised changes from https://github.com/neontribe/www/issues/49**

- [ ] Remove 'The Problem'
- [ ] Add footer to every page
- [ ] Add twitter information
- [ ] Add names to front of image tiles on 'The Tribe'
- [ ] Remove 'Join The Tribe' link from front page

##

![Front Page - 26th March](https://user-images.githubusercontent.com/41140803/55006761-2c84b100-4fd6-11e9-802c-b45bbbc24ced.png)

##

![How We Work - 26th March](https://user-images.githubusercontent.com/41140803/55006774-33abbf00-4fd6-11e9-90ba-accac4745125.png)

##

![The Tribe - 26th March](https://user-images.githubusercontent.com/41140803/55006800-39a1a000-4fd6-11e9-9c58-635ae5f2b364.png)

**Comment by HedgehogHolly** [comment]
When the problem solved was removed from the front page, I think it makes it look a little bare? So as an idea i've done a quick alternative version where the image is bigger, pushing the text down which would allow for more copy if needed? Thoughts @katquatermass?  Since i'll potentially be doing the illustration we can have it at any size. 

![Front Page Alt - 26th March](https://user-images.githubusercontent.com/41140803/55008620-2512d700-4fd9-11e9-8796-4e52365933a0.png)

**Comment by katquatermass** [comment]
I think that can work. The crucial thing will be to not let us give you _lots_ of copy, even though the design means we could!  And so long as we don't allow the image get into the "I hate those websites which are all one image that you have to scroll past before you get to anything (desktop complaint I think)" size! Also looks like it might be easier to make responsive because essentially single column for that first part now?

But in general - my take on things design wise now we've got the stories narrowed down is "if the stories are covered, and you and Matt are happy, we should be happy"

**Comment by HedgehogHolly** [comment]
Here is the wireframe with updated visuals including an idea of what it might look like on mobile. 

[MVP - Visual Design](https://github.com/neontribe/www/files/3025420/MVP_March_Colour.pdf)

**Comment by HedgehogHolly** [comment]
## Does the design meet the requirements of the user stories?

**Top 5 Userstories**

- [ ] As Shaii, I want to see a culture that supports individuality so that I know that I will be able to fit in.

- [ ]  As Neontribe, I want to use the website when convincing clients we can handle their design as well as development work, so that we deliver whole projects more often.

- [ ]  As Brian, I want to understand the process neontribe use to deliver projects so that I feel confident they can deliver on our project.

- [ ] As Brian, Jess and Terrance, I want to get the impression that Neontribe know what they are doing so that I feel confident in working with them.

- [ ] As Jess, I want to see other third sectors digital journeys so that I am confident that tech will help the people I work with

_______


- [ ] As Mike, I want to see names and pictures of Neontribe staff so that I can find the person I spoke to at a previous conference or meetup

- [ ] As a neontriber I want to be able to revise the description of what I do at neontribe so that I can keep it up to date and accurate.

- [ ] As Mike, I want to see evidence of Neontribe's involvement in conferences, so that I can see if they will fit into my events and would be interested in speaking/volunteering or even sponsoring

- [ ] As Terrance Smith, I want the website to look good on my phone or iPad so that I can use the website on whatever device I choose whenever I want.

- [ ] As a neontriber I want the website to be updated regularly so that I am not embarrassed by the lack of activity on the website.

- [ ] As Jess, I want to see that Neontribe have worked with funding bodies before so that I can strengthen my funding application

- [ ] As Mrs Jones, I want to see whether Neontribe take on interns/students and how they look after them, so that I know that I won't waste my time contacting them.

- [ ] As Brian, I want to see that they have worked on a variety of project so that I can see a diverse range of skills.

- [ ] As a neontriber I want to do my work on this website in the same way I work on other projects so that it makes things more simple.

- [ ] As Shaii, I want to know how to apply for a job at Neontribe so that I can apply

- [ ] **Not MVP** As a neontriber I want some kind of guideline for blogging so that I feel more comfortable writing a blog post.

- [ ] **Not MVP** As a neontriber I want the blogs to be easy to find so that people interested in my blogs are able to find them amongst others.

- [ ] **Not MVP** As a neontriber I want to get my content approved and online so that it can be seen without delay 

- [ ] **Copy** As Jess, I want to understand why Neontribe are called Neontribe so that I can tell my collegaues so they stop asking

- [ ] As Terrance, Brian and Jess, I want to see what recent and relevant projects Neontribe have worked on, so that I feel confident that they can deliver what they promise.

- [ ] As Terrance Smith, I want to be able to find information I need quickly so that I am not wasting my time

- [ ] As Jess and Brian, I understand how Neontribe contract work for the third sector, so that I am confident that there no hidden costs of surprises.

- [ ] As Terrance, Mike and Shaii, I want to find their social media quickly so that I can see what they have been doing lately.

- [ ] As a neontriber I want quick way to see the address so that I can get deliveries to the office easily

- [ ] *As Brian and Jess, I want to see they have worked with big name clients so that I feel reassured working with them.

**Comment by HedgehogHolly** [comment]
I think the stories the design doesn't meet is: 

1. As Mike, I want to see evidence of Neontribe's involvement in conferences, so that I can see if they will fit into my events and would be interested in speaking/volunteering or even sponsoring

2. As Terrance, Mike and Shaii, I want to find their social media quickly so that I can see what they have been doing lately.

The first story would have been answered with the blogs but with the current design I am not sure how to answer that story.  For the second story the only way to see our social media which is currently only twitter is in the footer, is that sufficient enough to answer the story?

**Comment by katquatermass** [comment]
1. We can write up one or two speaking initiatives as projects - then that will cover 1 until we have got blogs working again (I don't think we'll be long without it - it was too strong a "thing I need to be able to do" story for Neontribe employees so that even if it doesn't meet MVP it'll meet soon after MVP)
2. I think the Neontribe twitter link is sufficient - as that is the one we are currently confident looks busy enough and b) most likely for T, M and Shai to be using I think?  Over time we can meet that story better

**Comment by katjam** [comment]
@HedgehogHolly am re-carding futher actions seperately to make it easier to follow.

**Comment by katjam** [comment]
Further actions to re-card:

We can write up one or two speaking initiatives as projects - then that will cover 1 until we have got blogs working again (I don't think we'll be long without it - it was too strong a "thing I need to be able to do" story for Neontribe employees so that even if it doesn't meet MVP it'll meet soon after MVP)
Will make call to action more obvious
Will discuss problem/ solution / description copy on How we work page. Particularly for the design we need to know how many blocks of text
Will put logos in hexagons (not too worried about the legal implications on 'logo' design - since they will all be framed the same it should be obvious is not part of logo design. If it causes issue with funders - we can think again/ change the design.
Use 3 words to describe selves / job on front of people cards
