### ISSUE TITLE
Front Page: The Tribe's Experiences

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#56]
### **What needs doing?**
Three people need to be selected and they need to write about their experiences at neontribe, or how they came to join neontribe or both.

- [x] @katjam 
- [x] @RpprRoger 
- [x] @roseb04 

**Kat's guide** 
The front page story format is:  "I was doing X when Y and now I Z. it's great here because Q"

X is the interesting route in 
Y is how I met Neontribe
Z is what I do here now
Q is a bit of company flexibility that helps my work.

### Image of where text will be
![Screenshot 2019-06-19 at 14 44 30](https://user-images.githubusercontent.com/41140803/59771026-e40d2480-92a0-11e9-8ee6-15f05b15364b.png)

### Related user stories 

- As Shaii, I want to see a culture that supports individuality so that I know that I will be able to fit in.
- As Mrs Jones, I want to see whether Neontribe take on interns/students and how they look after them, so that I know that I won't waste my time contacting them.

**Comment by katjam** [comment]
I thought this would be 3 random of all of us and draw the info from the bio on the people page. We discussed not wanting to 'highlight' anyone in particular, same as the 'featured blog', 'featured project' issue.

@katquatermass @HedgehogHolly Did you discuss that these should be different content?

**Comment by katjam** [comment]
I wonder if it would be useful to create a mock-up (in future) that gave copy intent as well as squiggly lines - like we do for images.

**Comment by katquatermass** [comment]
We need to rewrite all blurbs into the format designed at the flow session which highlights: Where I came to Neontribe from; what I benefit from in Neontribe working practices; Anything else I want to highlight...   Because that was what we saw as meeting the "join this company" story.   Discussion waas it could be everyone randomly OR specific people chosen because their route to the company is interesting

**Comment by katquatermass** [comment]
So we have the copy intent - its just in the process notes somewhere

**Comment by HedgehogHolly** [comment]
@roseb04 has said she is happy to help write the stories for @katjam and @RpprRoger if you can spare some time to have a chat with her

**Comment by katquatermass** [comment]
Not me that decided they should be different - but overall difference
between nature of copy on the front and inside. On the front they need to
follow a structured format because they have a purpose of showing off
company diversity in particularly selected ways that will resonate, on the
full page they're shorter, peoples own choice content.  I guess the
ultimate will be everyone has a front page copy eventually - but we talked
collectively in the session that designed their structure about how the
most unusual routes in are the most important ones.

*Kat QuatermassService and Strategy Design*
Neontribe
Kat@neontribe.co.uk
0789 1487375

**Comment by harryharrold** [comment]
Some draft words... @katjam @RpprRoger @roseb04  - are these OK?

Katja - https://docs.google.com/document/d/1Vpi33yeieEFS-Y3SwLOzof4ONe_qY80aIXtOhVAkbzA/edit#heading=h.1fhlgzbjgtse

Rose - https://docs.google.com/document/d/1Vpi33yeieEFS-Y3SwLOzof4ONe_qY80aIXtOhVAkbzA/edit#heading=h.v3h3uovfwaq

Rob - https://docs.google.com/document/d/1Vpi33yeieEFS-Y3SwLOzof4ONe_qY80aIXtOhVAkbzA/edit#heading=h.5fu4fl926pec

...and then we'll do everyone else.
