### ISSUE TITLE
The Tribe: People's Bio

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#68]
### **What needs doing?**
- Photo
- Name
- Three words to show skills/interest
- Bio

### Image of where text will be
![Screenshot 2019-05-17 at 11 03 47](https://user-images.githubusercontent.com/41140803/58163964-d00fdc00-7c7c-11e9-8aea-712733c25bd1.png)

### Word count suggestion (Bio)
**Minimum:** 20 words
**Maximum:** 75 words  (more than 35 causes overflow) 

### **Plan**
- [x] HARRY HARROLD
- [x] RUPERT REDINGTON
- [x] NEIL DABSON
- [x] TOBY BATCH
- [x] MATT LAYTON
- [x] KATJA MORDAUNT
- [x] KARL JERMY
- [x] ANDY BARNES
- [x] ROBERT PREUS-MACLAREN
- [ ] OLIVER BARNWELL
- [x] KARA LANGFORD
- [x] GEORGE DEEKS
- [x] CHARLIE STRANGE
- [x] ALEXANDRA MOORE
- [x] ROSE BONNER
- [x] HOLLY STRINGER
- [x] KAT QUATERMASS
- [x] ED PERKINS
- [x] NICK WADE
- [x] AMANDA RASOLOFOTSARA
- [x] STEVE

### Related user stories 

- As Shaii, I want to see a culture that supports individuality so that I know that I will be able to fit in.
- As Mrs Jones, I want to see whether Neontribe take on interns/students and how they look after them, so that I know that I won't waste my time contacting them.
- As Mike, I want to see names and pictures of Neontribe staff so that I can find the person I spoke to at a previous conference or meetup

**Comment by katjam** [comment]
I thought @katquatermass had a plan for these that involved extracting people's journey into Neontribe, experience in Neontribe and some info outside of work. We discussed some sort of 'template/ guidelines' that included what tools we use to work etc.

Also - thought 'photo' could be any image with eyes (or something...)?

Is likely to be worth taking the time to link the copy tickets to out research and user story specifications where relevant. There was quite a lot in this next stage that we were hoping to cover by having constructed copy carefully.

Would be a shame to lose that.

**Comment by katquatermass** [comment]
Yes copy tickets MUST be linked to user stories.  And we had a lot of images discussion.  We can probably make suggestions based on people's current entries/what we know about them - but I don't have time to do that soon.  I do have a copy writer in Glasgow that we could send some to with the desired format and see if she can work just from the existing text into that shorter and sharper?  affordable rates, I expect @harryharrold would sign it off

**Comment by katquatermass** [comment]
But these ones on this page won't fit the full original copy plan, need to go back to that "what says diversity but professionalism fast" for this page

**Comment by katquatermass** [comment]
Have put a proposal into the slack channel for the flip view content to be written from existing copy, using user acceptance criteria by a content writer.

The front page tribe member stories is where we want the specific format mentioned by Katja above - I'll put more comments about that into the issue related to that.

**Comment by katquatermass** [comment]
Right. So before @HedgehogHolly gets started on first draft, 3 questions:

1) are we agreed that the format on THESE bios is one or two sentences in a style that reflects the individuals own and covers diversity of personality and interests whilst the format of "route to joining the company, thing about the company culture I value, side note with a quirky angle" is for front page member of tribe content only? Or do we want both to be the same?

2) The user stories the COPY should meet are:
Shaii - see a culture of individuality so that I know I would fit in
Jess/Brian/Terrance - I want to get the impression they know what they are doing, so I have confidence in working with them (projects page will deliver this, but people page must back it up)

3) The bios can't specifically meet mrs jones about will they take MY intern or WExp person - but can give an indication (as some folks will mention that journey) that she should look for further information.

Need @katjam and @harryharrold to confirm understanding probably?

**Comment by harryharrold** [comment]
1. Yes. 
2. Yes.
3. Yes

**Comment by HedgehogHolly** [comment]
I was also wondering how the bios should be written, currently they are all in third person should we stick to that format?

**Comment by katquatermass** [comment]
We don't have to. Convention is 3rd person for professional stuff 1st for
social media and the lines between the two are blurring more and more.
First person is likely to make some people feel squirmy about them though.


*Kat QuatermassService and Strategy Design*
Neontribe
Kat@neontribe.co.uk
0789 1487375

**Comment by katjam** [comment]
I think 3rd is OK.

On your 1. 2. 3....

1- Yes and I think we want the sentence used for front page to be repeated on the people page... but the front need not contain all the text.

2- Yes and wasn't there a story about people wanting to know what tech we use? We can optionally cover some of that here and in project blurbs.

3- Yes perfect - some people's bios should hit those.

**Comment by katquatermass** [comment]
I think my understanding and yours of the relationship between front page and back page is different Katja-  there's more words and space for the joining story on the front page - the people page should be more about whatever short thing people want to use to individually describe themselves.

The front page story format is "I was doing X when Y and  now I Z. it's great here because Q"
Where X is the interesting route in Y is how I met Neontribe and Z  is what I do here now and Q is a bit of company flexibility that helps my work.

**Comment by HedgehogHolly** [comment]
I've created a google doc where everyone can add their information: [Google Doc](https://docs.google.com/document/d/1Vpi33yeieEFS-Y3SwLOzof4ONe_qY80aIXtOhVAkbzA/edit?usp=sharing)

We are collecting the images in a [Google Drive Folder](https://drive.google.com/drive/folders/1h8_9pjrPO6AkGIuTVNuh_oOQps8Rkz_c?usp=sharing)
