### ISSUE TITLE
Website Review

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#70]
This is the current progress of the website. 

**Website link:** **https://hedgehogholly.github.io/www**

_The white square will be an illustration that expresses what Neontribe do._

Welcoming any comments.

**Resources**
-[paper prototype](https://github.com/neontribe/www/issues/43#issuecomment-472403767)

**Notes**
-call to actions get lost?
-problem and solution not working?
-funders logos in hexagons instead of circles?
-job titles on the front of tribe images as well as back?
-job titles could be three descriptive words?

**Comment by katquatermass** [comment]
Great to see progress.

I struggle with calls to action being smaller or same size text than main reading text - I think they get lost, making it harder for users to decide whether they can skip blurb or not.  It MIGHT be exacerbated by loren ipsum but I think it isn't just that. Would love to know how others feel, it could easily be a just me thing - or a "enough just me to want to verify with a usability test"

I think at the moment something weird is going on with the hexagons where the wrap is dependent on how much text in a particular line - meaning colour sneaks into a project block. I suspect it would be easier to see beginning an end of projects if hexagons were beaten by overall rectangle not how much text?   

I think elsewhere you've asked about shortening copy? The projects will look better if the content is shortened. We can work on that. I don't like having just links, without explaining what you find there (as the links to our different projects are different things - some go to a website that explains the tool, some are the tool - so I'd like to bring back sentences around those whilst reducing the other content.
Problem and Solution would need to go underneath the quote, and then be followed by the blurb in order to make any sense.  But they might well also allow us to reduce the rest of the blurb.   Depends if people want us to stick to that format.

**Comment by HedgehogHolly** [comment]
> **Throughout**
> I struggle with calls to action being smaller or same size text than main reading text 

I can understand that, I'm happy to play around with it see if making them a slightly bigger font size than the main text might help?

> **How we Work/Our Work**
> I think at the moment something weird is going on with the hexagons where the wrap is dependent on how much text in a particular line 

Im not quite sure what you mean? But I do agree it can be hard to see where the beginning and end of a project start

> I think elsewhere you've asked about shortening copy? 

I've suggested slightly shorter descriptions for some of the projects. Only based on the fact I thought  we were trying to focus on highlighting the problem and solution as being the important part of the project so I don't see us needing a long description to go with it. 

> Problem and Solution would need to go underneath the quote. Depends if people want us to stick to that format of problem solution.

The Problem and Solution only went underneath as that was what was in the [prototype](https://github.com/neontribe/www/issues/43#issuecomment-472403767).  I do feel like generally the Problem and Solution isn't working too well, it gets lost as just plain text (not of any importance) and might benefit from some sort of focus/highlighting to draw peoples eye to it or shown in a different format.

> Funders may not like logos being displayed as circles when their logo isn't a circle. Hexagons may help a bit both with space but also with the why being "because this is the design, and we know you'll want it as big as we can get it".

This makes sense, I think Rob also suggested this earlier when he saw the designs. I am happy to changed the logos to hexagons. 

> **The Tribe**
> I think there could be an improvement to our quick glance what we do as a company and how diverse we are stories, if the caption was name and job title, not just name.

Having both the name and title on the front? I think the reason behind not doing that originally is because I know a lot of people seemed to feel funny about 'job titles' so I didn't want to bring a lot of focus to them. I would have to jiggle some stuff around to make it work but I can definitely do that if that is the general consensus

**Comment by katjam** [comment]
> Problem and Solution would need to go underneath the quote. Depends if people want us to stick to that format of problem solution.

>The Problem and Solution only went underneath as that was what was in the prototype. I do feel like generally the Problem and Solution isn't working too well, it gets lost as just plain text (not of any importance) and might benefit from some sort of focus/highlighting to draw peoples eye to it or shown in a different format.

Agree - hexagons

**Comment by katjam** [comment]
Funders may not like logos being displayed as circles when their logo isn't a circle. Hexagons may help a bit both with space but also with the why being "because this is the design, and we know you'll want it as big as we can get it".

>This makes sense, I think Rob also suggested this earlier when he saw the designs. I am happy to changed the logos to hexagons.

Agree - try with hexagons

**Comment by katjam** [comment]
>The Tribe
>I think there could be an improvement to our quick glance what we do as a company and how diverse we are stories, if the caption was name and job title, not just name.

>Having both the name and title on the front? I think the reason behind not doing that originally is because I know a lot of people seemed to feel funny about 'job titles' so I didn't want to bring a lot of focus to them. I would have to jiggle some stuff around to make it work but I can definitely do that if that is the general consensus

We don't really have meaningful job titles (for the most part) - but something fun like 3 'descriptive' words we choose ourselves might work. For the record: I'd be against Job titles even if we had / or came up with better ones - because feels labelly / boxed in and corporate.

**Comment by alexalala** [comment]
Sorry if you've covered any of this off in the meetings! Feedback below ->

I think the blocks of text are too blocks-of-texty, some more line-height I think would make them more readable, but I'm not sure if we've explored a 'read more' option, to give a nice summary for each project and then allow for further detail if needed?

![Screenshot 2019-05-03 at 15 37 38](https://user-images.githubusercontent.com/11891294/57144694-82106280-6db9-11e9-8779-9a488da31b2d.png)

Also the links could look a bit more like interactive elements, rather than just blending into the text.

Also Alexand**ra** Rose is Alexand**ra** 🙃

**Comment by katjam** [comment]
Agreed in Catchup 7 May #54 :

- Will make call to action more obvious (carding for ideas)
- Will discuss problem/ solution / description copy on How we work page. Particularly for the design we need to know how many blocks of text
- Will put logos in hexagons (not too worried about the legal implications on 'logo' design - since they will all be framed the same it should be obvious is not part of logo design. If it causes issue with funders - we can think again/ change the design.
- Use 3 words to describe selves / job on front of people cards
