### ISSUE TITLE
How we work page

### ISSUE THREAD

**Issue by katjam** [neontribe/www#75]
**What needs doing?**
During #70 and #54 We talked about the problem/ solution text not working as it was designed originally as a teaser leading to more project info.

Thoughts on if we could use the concept within the description of project.

In terms of design for now - we need to know number of blocks of text - but not copy content necessarily.

Might be good to try with one project in terms of copy to get an idea of what might work.

@katquatermass @roseb04 @harryharrold  This one might be something you have thoughts about.

**Comment by katquatermass** [comment]
Can't be in the meeting, I'll be on a train to London - my thoughts in bullet points here:

- The essential thing that will meet the user stories about trusting us/understanding our projects are like what we want to do can be met at minimum viable level by "short snappy content that displays well on a page"

- I'm strongly against pausing the project again to test description versus problem/solution content type because I think the difference will be minimal and vary in a complex way among users

- I think we should decide content type in a channel poll for

1. current format with body copy edited to word count 
2. Format of Problem, Solution (and optionally testimonial depending on Holly's decision on space)

- Once decided Holly should set word limits that make the design work well as a single page. I can then edit copy to the chosen format and length. I have time to do this next week as SSSP has changed how it is content writing

- Since we are developing our expertise in content research, we can, later in the year if we have a window, test some variant project content formats in wire frame with carefully chosen organisations and update design to reflect that then (including creating some longer form click through versions for testing)



-

**Comment by HedgehogHolly** [comment]
Just interesting to know, David the designer for Lola who is also re-designing their own company's website said: 

The work area is something we're struggling with ourselves.

At this point we have structured the page to have three main paragraphs (problem, approach, outcome), a potential gallery (we are using a carousel which allows us to have anywhere from 1 to 10 images without affecting the page template layout) and a title + an introductory (summary) phrase. This allows us to have content for each case study with not many scalability issues. We can even remove that carousel if there are no visuals for the project.

**Comment by katquatermass** [comment]
Not an MVP solution, but I quite like it if/when we're ready to go to full pages.
My instinct is that "problem, approach, outcome" probably leads to longer content than most users want to read unless the copywriters are very good, but its definitely one to consider.

**Comment by HedgehogHolly** [comment]
Yes I agree, probably not MVP solution and definitely would lead to longer copy which we don't necessarily have time to write now but I do like 'problem, approach, outcome' compared to 'problem and solution'

**Comment by HedgehogHolly** [comment]
Discussions from Catch up meeting 14th May #76 

**Result of disscussion:**
- We decided to move forward with the second option - problem and solution only but without the restriction one sentence for each

**Actions**
- Come up with designs that showcase only problem and solution
- Decide which design to move forward with 

Review on the 21st May #82

**Comment by HedgehogHolly** [comment]
[Mobile - Closed](https://user-images.githubusercontent.com/41140803/57788062-59c82280-772e-11e9-8a9e-48dc364c6882.jpg)


[Mobile Before]((https://user-images.githubusercontent.com/41140803/57788062-59c82280-772e-11e9-8a9e-48dc364c6882.jpg))
![Long Text Mobile 2](https://user-images.githubusercontent.com/41140803/57788063-59c82280-772e-11e9-9d11-e148ef32bf0d.jpg)
![Long Text 2](https://user-images.githubusercontent.com/41140803/57788064-59c82280-772e-11e9-96e4-d8790764556e.jpg)
![Long Text 1](https://user-images.githubusercontent.com/41140803/57788066-5a60b900-772e-11e9-85ab-2013719d0687.jpg)

**Comment by katjam** [comment]
@HedgehogHolly Looks awesome. Great compromise - we can add a few case studies situated somewhere else if we find people wanting more detail later.

**Comment by roseb04** [comment]
**Acceptance Criteria**
- [ ] When I read the description I get a sense of the company culture.
- [ ] As a developer, I recognise (some of) the things I love about the project in the solution.
- [ ] Jess now understands that Neontribe ...
- ... works with service users
- ... do test and learn
- ... know what else is going on in tech
- ... understand things I don't 
- ... can work with hard to reach groups
- ... get GDPR and cyber security 
- ... collaborates well with other charities

**Tone**
- Language is active (we did, not it was done)
- Language is collaborative (we, not they or I)
- Language is direct and specific ("Hit a deadline" not "Meet a deadline")
- Language is not overly formal (contractions are fine)
- Language is varied ( we don't always use the same word formula to describe the same activity)
- Language is conversation (should sound fine if read aloud)

**Comment by harryharrold** [comment]
Word count suggestion (Description)
Minimum: 10 words
Maximum: 30 words

Word count suggestion (Problem and Solution)
Minimum: 10 words
Maximum: 30 words

**Comment by RpprRoger** [comment]
This looks like this was considered during the redesign #97 and we have copy/content tracking cards, #98. Closing this for now.
