### ISSUE TITLE
Front Page Illustration

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#79]
I’ve been working on the front page illustration and this is what I’ve created

Each part is representing elements of what we do, paper prototyping/ux, front-end/design. codey stuff/back-end

Harry’s suggested that it might work better if the paper prototype looked more like a user journey as its a bit too similar to a wireframe?

Would appreciate any other comments

**1st Version**
![neontribe_illustration](https://user-images.githubusercontent.com/41140803/57468976-76bbac00-727d-11e9-9dbf-93e651772b5a.jpg)

**2nd Version**
![neontribe-illustration](https://user-images.githubusercontent.com/41140803/57630657-e7243f00-7595-11e9-8500-4a770326e210.jpg)

**Comment by katjam** [comment]
I think it looks ace. I have no idea how -but would be nice to get across collaboration with users and clients.

Agree with @harryharrold that the paper prototype looks more digital wireframe-y.

**Comment by harryharrold** [comment]
+1 to "that left hand element being more clearly collaborative"

Also.... left hand element as a user journey, yes, rather than a prototype. I think coding might usefully be placed centrally and polishing on the right?

If we can additionally illustrate "usability testing" on the right - then excellent!

**Comment by roseb04** [comment]
I think it looks great as well!

I know what you mean Katja, maybe there could be a person pointing at the wire frame and then it looks like the person making notes is observing. 

I don't know, I think it looks paper-y, I can imagine Holly can make it look more like paper with some special graphics. I suppose you could combine the first and the second. And then add user journeys. Here's some user journey illustrations I like :) (and yes I did steal them from the Jeff Patton book on story mapping)

![image](https://user-images.githubusercontent.com/44296500/57469913-9c49b500-727f-11e9-96d4-68f0d21fd207.png)

![image](https://user-images.githubusercontent.com/44296500/57469934-a4a1f000-727f-11e9-8620-833570ae03e1.png)

**Comment by katjam** [comment]
I think both user journey mapping and prototyping in paper are core to what we do. The paper is more collaborative and unusual. The journey mapping is pretty on trend... but if we can incorporate both and a usability test session?

**Comment by katjam** [comment]
I realise I am asking for all the things... but is it worth making it more iterative than linear?

**Comment by katjam** [comment]
Or would it be enough to have images of the journey map and user sessions in thought bubbles of the people making the stuff?

**Comment by charlesstrange2** [comment]
If it were iterative, you'd need a test/user test section that wrapped back to the thinking bit.

Does there need to be a discovery slide where our figures point at post it's on a wall and puzzle it out to client figures? Possibly with abstract model "ideas" floating around the room?

**Comment by HedgehogHolly** [comment]
Although I can see where you are coming from I think it will over complicate the simplicity of the illustration if we start adding too much to it. 

I think theres only so much we can show in one illustration but we can always add other illustrations throughout the website to show how we work, maybe on the process page if we get around to adding it.

I'll work on moving the order of the sections and changing the paper prototype to more of a user journey. Then see what we think of the next draft of the illustration.

**Comment by charlesstrange2** [comment]
Aha!

That first one looks good now!

**Comment by katquatermass** [comment]
I agree with not adding too much. 
I thought about things like adding arrows that show we are doing cycles of testing and learning and similar and then realised we should think back to what the image is meant to do.  
It's think its main user story purpose is "I've found the company that does software development that I met at a conference/that someone recommended to me" and I think it achieves that.
We could - if we wanted to (and because it would showcase our illustration skills as a company) over time, build up a suite of different images in different styles that do that in different ways - each showing the picture in different ways.

**Comment by Kurgol** [comment]
I love it =)

**Comment by HedgehogHolly** [comment]
I believe this can be closed for now? @katjam

**Comment by katjam** [comment]
Yep. Close.

**Comment by katjam** [comment]
@HedgehogHolly Why did we ditch this?

**Comment by katquatermass** [comment]
Ditched in peer review of the website when Rich Len visited. 

The image doesn't do what we first thought it might. It doesn't read rapidly as a snapshot of "Neontribe is a digital agency".  It reads as an interesting infographic on what process is - but takes time to absorb if you are not us, and slows a user's engagement with the website down. (something we also discovered in parallel in the safeguarding research - people take a lot of time to "read" images if they have any complexity at all)

We think it is an ideal image for a process page or process blog when we add one, so rather than being totally closed it should resurface in the project board for ongoing.

**Comment by katjam** [comment]
Ah fair enough. I was sad about it going - since I thought it lended a bit
of personality. I look forward to its resurfacing!
